version: '3.9'

# Docker Compose for TelDrive Development
# Extends production config and overrides only what's needed for development
# Automatically loads environment variables from .env file

services:
  # Extend database from production with dev overrides
  db:
    extends:
      file: docker-compose.yml
      service: db
    container_name: teldrive_db_dev
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-devpassword}
    volumes:
      - 'pgdata_dev:/var/lib/postgresql/data'
    ports:
      - "5432:5432"  # Expose DB port for development tools

  # Extend teldrive app from production with dev overrides
  teldrive:
    extends:
      file: docker-compose.yml
      service: teldrive
    container_name: teldrive_app_dev
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UI_SOURCE_TYPE=build
        - UI_REPO_URL=https://github.com/cdgmx/teldrive-ui.git
        - UI_REPO_BRANCH=main
        - BUILD_MODE=development
    environment:
      # Development-friendly defaults (inherits others from production)
      - TELDRIVE_JWT_SECRET=${TELDRIVE_JWT_SECRET:-dev-jwt-secret-key-for-local-development-only}
      - TELDRIVE_JWT_ALLOWED_USERS=${TELDRIVE_JWT_ALLOWED_USERS:-YourTelegramUsername}
      - TELDRIVE_TG_UPLOADS_ENCRYPTION_KEY=${TELDRIVE_TG_UPLOADS_ENCRYPTION_KEY:-dev-32-char-encryption-key-local}
      - TELDRIVE_CACHE_REDIS_PASS=${TELDRIVE_CACHE_REDIS_PASS:-}
    ports:
      - "8080:8080"  # Main application port

  # Extend imgproxy from production with dev overrides
  imgproxy:
    extends:
      file: docker-compose.yml
      service: imgproxy
    container_name: teldrive_imgproxy_dev
    restart: unless-stopped
    environment:
      IMGPROXY_ALLOW_ORIGIN: "*"  # Allow all origins for development
      IMGPROXY_ENFORCE_WEBP: 'true'
      IMGPROXY_MALLOC: jemalloc
    ports:
      - "8000:8080"  # Image proxy port

# Import configs from production
configs:
  teldrive_config:
    content: |
      [db]
      data-source = "postgres://teldriveadmin:${POSTGRES_PASSWORD:-devpassword}@db:5432/teldrive"

volumes:
  pgdata_dev: