// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	AuthLoginOperation          OperationName = "AuthLogin"
	AuthLogoutOperation         OperationName = "AuthLogout"
	AuthSessionOperation        OperationName = "AuthSession"
	AuthWsOperation             OperationName = "AuthWs"
	EventsGetEventsOperation    OperationName = "EventsGetEvents"
	FilesCategoryStatsOperation OperationName = "FilesCategoryStats"
	FilesCopyOperation          OperationName = "FilesCopy"
	FilesCreateOperation        OperationName = "FilesCreate"
	FilesCreateShareOperation   OperationName = "FilesCreateShare"
	FilesDeleteOperation        OperationName = "FilesDelete"
	FilesDeleteShareOperation   OperationName = "FilesDeleteShare"
	FilesEditShareOperation     OperationName = "FilesEditShare"
	FilesGetByIdOperation       OperationName = "FilesGetById"
	FilesListOperation          OperationName = "FilesList"
	FilesMkdirOperation         OperationName = "FilesMkdir"
	FilesMoveOperation          OperationName = "FilesMove"
	FilesShareByidOperation     OperationName = "FilesShareByid"
	FilesStreamOperation        OperationName = "FilesStream"
	FilesUpdateOperation        OperationName = "FilesUpdate"
	FilesUpdatePartsOperation   OperationName = "FilesUpdateParts"
	SharesGetByIdOperation      OperationName = "SharesGetById"
	SharesListFilesOperation    OperationName = "SharesListFiles"
	SharesStreamOperation       OperationName = "SharesStream"
	SharesUnlockOperation       OperationName = "SharesUnlock"
	UploadsDeleteOperation      OperationName = "UploadsDelete"
	UploadsPartsByIdOperation   OperationName = "UploadsPartsById"
	UploadsStatsOperation       OperationName = "UploadsStats"
	UploadsUploadOperation      OperationName = "UploadsUpload"
	UsersAddBotsOperation       OperationName = "UsersAddBots"
	UsersCreateChannelOperation OperationName = "UsersCreateChannel"
	UsersDeleteChannelOperation OperationName = "UsersDeleteChannel"
	UsersListChannelsOperation  OperationName = "UsersListChannels"
	UsersListSessionsOperation  OperationName = "UsersListSessions"
	UsersProfileImageOperation  OperationName = "UsersProfileImage"
	UsersRemoveBotsOperation    OperationName = "UsersRemoveBots"
	UsersRemoveSessionOperation OperationName = "UsersRemoveSession"
	UsersStatsOperation         OperationName = "UsersStats"
	UsersSyncChannelsOperation  OperationName = "UsersSyncChannels"
	UsersUpdateChannelOperation OperationName = "UsersUpdateChannel"
	VersionVersionOperation     OperationName = "VersionVersion"
)
