// Code generated by ogen, DO NOT EDIT.
package api

type AuthSessionRes interface {
	authSessionRes()
}

type FilesStreamRes interface {
	filesStreamRes()
}

type SharesStreamRes interface {
	sharesStreamRes()
}
